name: Rust Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Rust Library
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose
      working-directory: rustlib

    - name: Run tests
      run: cargo test --verbose
      working-directory: rustlib

    - name: Run clippy
      run: cargo clippy -- -D warnings
      working-directory: rustlib

    - name: Check formatting
      run: cargo fmt -- --check
      working-directory: rustlib

  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose
      working-directory: rustlib

    - name: Run tests
      run: cargo test --verbose
      working-directory: rustlib

  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install vcpkg and OpenSSL (Windows)
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg install openssl:x64-windows
        echo "VCPKG_ROOT=$PWD" >> $env:GITHUB_ENV
      shell: powershell

    - name: Set up OpenSSL env vars (Windows)
      run: |
        echo "OPENSSL_DIR=$env:VCPKG_ROOT\installed\x64-windows" >> $env:GITHUB_ENV
        echo "OPENSSL_LIB_DIR=$env:VCPKG_ROOT\installed\x64-windows\lib" >> $env:GITHUB_ENV
        echo "OPENSSL_INCLUDE_DIR=$env:VCPKG_ROOT\installed\x64-windows\include" >> $env:GITHUB_ENV
        echo "PATH=$env:VCPKG_ROOT\installed\x64-windows\bin;$env:PATH" >> $env:GITHUB_ENV
      shell: powershell

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Build
      run: cargo build --verbose
      working-directory: rustlib

    - name: Run tests
      run: cargo test --verbose
      working-directory: rustlib 